### PR TITLE
TS-1537: Fixing merge conflicts between master and release

### PR DESCRIPTION
**Pull request by martapederiva**
🐻 with me on this one...
A few days ago [I merged a PR to release from a different branch than master](https://github.com/LBHackney-IT/housing-search-api/pull/246) (as master had changes we didn't want to push up yet). Now I want to merge master into release, however GitHub [flags a merge conflict](https://github.com/LBHackney-IT/housing-search-api/compare/release...master?expand=1). This PR aims to fix it, since I cannot merge release into master, as [that would drag in tons of ancient stuff](https://github.com/LBHackney-IT/housing-search-api/compare/master...release?expand=1).

### CODE REVIEW

**Comment by Duslerke** [comment]
Has that PR that went from `other` to `release` been merged into `master`?

The link shared at the end of a diff between `release` and `master` shows that `master` is missing some changes that amount to **23 additions and 1 deletion**.

**Review by Duslerke — COMMENTED** [review]
If the linked diff between the `release` and `master` is correct...

Meaning `release` actually has some changes that skipped the `master` branch,
Then perhaps, it would actually be better to merge the `release` into `master`?

Most of those other commits are just merge markers that have no real effect on master apart slightly tainting the git history.

Not 100% sure on this, but you may be even able to avoid moving these merge markers into `master` if you do a **Squash Merge** from `release` into `master` instead. So moving just the missing changes _(assuming they're actually missing & it's not a diff glitch)_ & none of the commits apart the squash merge commit.

**Comment by martapederiva** [comment]
> Has that PR that went from `other` to `release` been merged into `master`?

Yes, it's [this one.](https://github.com/LBHackney-IT/housing-search-api/pull/245/files)
+23 -1

I feel very silly no not to have noticed that there were a lot of commits in release vs master, but just the 3 files I was interested in anyway 🤦

**Comment by Duslerke** [comment]
>  that there were a lot of commits in release vs master

Most of those commits are meaningless as all they do is show that a merge happened - they don't contain any actual changes.
Any non-merge commits are the ones that are likely actually missing from `master` and are contributing to the file diff you see.

**Review by Duslerke — APPROVED** [review]

**Pull request merged**
